[package]
name = "prettify"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "An extensible, language-agnostic code formatter based on Prettier written in Rust."
readme = "README.md"

[dependencies]
regex = "1"

[dev-dependencies]
indoc = "1.0"
